name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1']
        magento-version: ['2.4.4', '2.4.5', '2.4.6']

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: json, gd, mysql, zip, intl, pdo_mysql
          coverage: none

      - name: Setup Composer Authentication
        env:
          MAGENTO_USERNAME: ${{ secrets.MAGENTO_MARKETPLACE_PUBLIC_KEY }}
          MAGENTO_PASSWORD: ${{ secrets.MAGENTO_MARKETPLACE_PRIVATE_KEY }}
        run: |
          echo "Creating auth.json in project directory"
          cat > auth.json << EOF
          {
            "http-basic": {
              "repo.magento.com": {
                "username": "$MAGENTO_USERNAME",
                "password": "$MAGENTO_PASSWORD"
              }
            }
          }
          EOF

          echo "Verifying auth.json exists and has content"
          ls -l auth.json
          cat auth.json | grep -v password | grep -v username

      - name: Install Dependencies
        env:
          COMPOSER_AUTH: ${{ toJson({"http-basic": {"repo.magento.com": {"username": "${{ secrets.MAGENTO_MARKETPLACE_PUBLIC_KEY }}", "password": "${{ secrets.MAGENTO_MARKETPLACE_PRIVATE_KEY }}"}}}) }}
        run: |
          echo "Using COMPOSER_AUTH environment variable"
          composer install --prefer-dist --no-progress -vvv

      - name: Run tests
        run: |
          vendor/bin/phpunit
          vendor/bin/phpcs
          vendor/bin/phpstan analyse
          vendor/bin/psalm
          vendor/bin/phpmd src text cleancode,codesize,controversial,design,naming,unusedcode

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create release archive
        run: |
          zip -r Sterk_GraphQlPerformance.zip app/code/Sterk/GraphQlPerformance

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Sterk_GraphQlPerformance.zip
          asset_name: Sterk_GraphQlPerformance.zip
          asset_content_type: application/zip
