name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1']
        magento-version: ['2.4.4', '2.4.5', '2.4.6']

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: json, gd, mysql, zip, intl, pdo_mysql
          coverage: none
          tools: composer
          ini-values: memory_limit=2G

      - name: Setup Composer Authentication
        run: |
          # Create auth.json with direct variable substitution
          echo '{
            "http-basic": {
              "repo.magento.com": {
                "username": "'${{ secrets.MAGENTO_MARKETPLACE_PUBLIC_KEY }}'",
                "password": "'${{ secrets.MAGENTO_MARKETPLACE_PRIVATE_KEY }}'"
              }
            }
          }' > auth.json

          # Set proper permissions
          chmod 600 auth.json

          # Show auth.json contents (masked)
          echo "Auth.json contents (masked):"
          cat auth.json | tr -d '\n' | sed 's/\("username": *"\)[^"]*\(".*\)/\1****\2/' | sed 's/\("password": *"\)[^"]*\(".*\)/\1****\2/'

      - name: Install Dependencies
        run: |
          # Install dependencies with verbose output
          composer -vvv install --prefer-dist --no-progress

      - name: Run tests
        run: |
          vendor/bin/phpunit
          vendor/bin/phpcs
          vendor/bin/phpstan analyse
          vendor/bin/psalm
          vendor/bin/phpmd src text cleancode,codesize,controversial,design,naming,unusedcode

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create release archive
        run: |
          zip -r Sterk_GraphQlPerformance.zip app/code/Sterk/GraphQlPerformance

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Sterk_GraphQlPerformance.zip
          asset_name: Sterk_GraphQlPerformance.zip
          asset_content_type: application/zip
