name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1']
        magento-version: ['2.4.4', '2.4.5', '2.4.6']

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: json, gd, mysql, zip, intl, pdo_mysql
          coverage: none

      - name: Setup Composer Authentication
        env:
          MAGENTO_PUBLIC_KEY: ${{ secrets.MAGENTO_MARKETPLACE_PUBLIC_KEY }}
          MAGENTO_PRIVATE_KEY: ${{ secrets.MAGENTO_MARKETPLACE_PRIVATE_KEY }}
        run: |
          # Create ~/.composer directory if it doesn't exist
          mkdir -p ~/.composer

          # Create auth.json with proper JSON escaping
          cat > ~/.composer/auth.json << 'EOL'
{
  "http-basic": {
    "repo.magento.com": {
      "username": "$MAGENTO_PUBLIC_KEY",
      "password": "$MAGENTO_PRIVATE_KEY"
    }
  }
}
EOL

          # Replace environment variables in auth.json
          sed -i "s/\$MAGENTO_PUBLIC_KEY/$MAGENTO_PUBLIC_KEY/g" ~/.composer/auth.json
          sed -i "s/\$MAGENTO_PRIVATE_KEY/$MAGENTO_PRIVATE_KEY/g" ~/.composer/auth.json

          # Set permissions
          chmod 600 ~/.composer/auth.json

          # Verify auth.json exists and has correct permissions
          ls -la ~/.composer/auth.json

          # Test authentication (without showing credentials)
          echo "Testing authentication..."
          curl -s -I -H "Accept: application/json" --user "$MAGENTO_PUBLIC_KEY:$MAGENTO_PRIVATE_KEY" https://repo.magento.com/packages.json | head -n 1

      - name: Install Dependencies
        run: |
          echo "COMPOSER_AUTH is set: $(test -n "$COMPOSER_AUTH" && echo yes || echo no)"
          composer config --list --global
          composer install --prefer-dist --no-progress -vvv

      - name: Run tests
        run: |
          vendor/bin/phpunit
          vendor/bin/phpcs
          vendor/bin/phpstan analyse
          vendor/bin/psalm
          vendor/bin/phpmd src text cleancode,codesize,controversial,design,naming,unusedcode

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create release archive
        run: |
          zip -r Sterk_GraphQlPerformance.zip app/code/Sterk/GraphQlPerformance

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Sterk_GraphQlPerformance.zip
          asset_name: Sterk_GraphQlPerformance.zip
          asset_content_type: application/zip
