name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1']
        magento-version: ['2.4.4', '2.4.5', '2.4.6']

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: json, gd, mysql, zip, intl, pdo_mysql
          coverage: none
          tools: composer
          ini-values: memory_limit=2G

      - name: Test Magento Authentication
        run: |
          # Test authentication directly with curl
          echo "Testing Magento authentication..."
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer ${{ secrets.MAGENTO_MARKETPLACE_PUBLIC_KEY }}:${{ secrets.MAGENTO_MARKETPLACE_PRIVATE_KEY }}" https://repo.magento.com/packages.json)
          echo "HTTP response code: $HTTP_CODE"

          if [ "$HTTP_CODE" = "200" ]; then
            echo "Authentication successful!"
          else
            echo "Authentication failed with code $HTTP_CODE"
            exit 1
          fi

      - name: Install Dependencies
        run: |
          # Create auth.json with environment variables
          echo "{
            \"http-basic\": {
              \"repo.magento.com\": {
                \"username\": \"${{ secrets.MAGENTO_MARKETPLACE_PUBLIC_KEY }}\",
                \"password\": \"${{ secrets.MAGENTO_MARKETPLACE_PRIVATE_KEY }}\"
              }
            }
          }" > auth.json

          # Show auth.json was created (without showing contents)
          ls -la auth.json

          # Move auth.json to composer home
          mkdir -p ~/.composer
          cp auth.json ~/.composer/

          # Configure Magento repository
          composer config repositories.magento composer https://repo.magento.com/

          # Install dependencies with verbose output
          COMPOSER_AUTH=$(cat auth.json) composer -vvv install --prefer-dist --no-progress --no-interaction

      - name: Run tests
        run: |
          vendor/bin/phpunit
          vendor/bin/phpcs
          vendor/bin/phpstan analyse
          vendor/bin/psalm
          vendor/bin/phpmd src text cleancode,codesize,controversial,design,naming,unusedcode

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create release archive
        run: |
          zip -r Sterk_GraphQlPerformance.zip app/code/Sterk/GraphQlPerformance

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Sterk_GraphQlPerformance.zip
          asset_name: Sterk_GraphQlPerformance.zip
          asset_content_type: application/zip
