name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1']
        magento-version: ['2.4.4', '2.4.5', '2.4.6']

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: json, gd, mysql, zip, intl, pdo_mysql
          coverage: none
          tools: composer
          ini-values: memory_limit=2G

      - name: Setup Composer Authentication
        run: |
          # Configure Composer authentication
          composer config --global http-basic.repo.magento.com "${{ secrets.MAGENTO_MARKETPLACE_PUBLIC_KEY }}" "${{ secrets.MAGENTO_MARKETPLACE_PRIVATE_KEY }}"

          # Verify configuration
          echo "Composer configuration:"
          composer config --global --list | grep -v password

          # Create auth.json for redundancy
          mkdir -p ~/.composer
          cat > ~/.composer/auth.json << EOL
          {
              "http-basic": {
                  "repo.magento.com": {
                      "username": "${{ secrets.MAGENTO_MARKETPLACE_PUBLIC_KEY }}",
                      "password": "${{ secrets.MAGENTO_MARKETPLACE_PRIVATE_KEY }}"
                  }
              }
          }
          EOL

          # Set proper permissions
          chmod 600 ~/.composer/auth.json

          # Verify auth.json
          echo "Auth.json contents (masked):"
          cat ~/.composer/auth.json | sed 's/"username": "[^"]*"/"username": "****"/g; s/"password": "[^"]*"/"password": "****"/g'

          # Test authentication
          echo "Testing authentication..."
          curl -s -I -H "Accept: application/json" --user "${{ secrets.MAGENTO_MARKETPLACE_PUBLIC_KEY }}:${{ secrets.MAGENTO_MARKETPLACE_PRIVATE_KEY }}" https://repo.magento.com/packages.json

      - name: Install Dependencies
        run: |
          # Show Composer configuration
          echo "Composer configuration:"
          composer config --global --list | grep -v password

          # Install dependencies with verbose output
          composer install --prefer-dist --no-progress -v

      - name: Run tests
        run: |
          vendor/bin/phpunit
          vendor/bin/phpcs
          vendor/bin/phpstan analyse
          vendor/bin/psalm
          vendor/bin/phpmd src text cleancode,codesize,controversial,design,naming,unusedcode

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create release archive
        run: |
          zip -r Sterk_GraphQlPerformance.zip app/code/Sterk/GraphQlPerformance

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Sterk_GraphQlPerformance.zip
          asset_name: Sterk_GraphQlPerformance.zip
          asset_content_type: application/zip
