name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1']
        magento-version: ['2.4.4', '2.4.5', '2.4.6']

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: json, gd, mysql, zip, intl, pdo_mysql
          coverage: none

      - name: Setup Composer Authentication
        run: |
          # Create auth.json with explicit values
          PUBLIC_KEY="${{ secrets.MAGENTO_MARKETPLACE_PUBLIC_KEY }}"
          PRIVATE_KEY="${{ secrets.MAGENTO_MARKETPLACE_PRIVATE_KEY }}"

          echo "Setting up auth.json with public key: ${PUBLIC_KEY:0:4}..."

          mkdir -p ~/.composer
          cat > ~/.composer/auth.json << EOF
          {
            "http-basic": {
              "repo.magento.com": {
                "username": "${PUBLIC_KEY}",
                "password": "${PRIVATE_KEY}"
              }
            }
          }
          EOF

          chmod 600 ~/.composer/auth.json

          # Verify auth.json contents (masking sensitive data)
          echo "Auth.json contents:"
          sed 's/\("username": "\)[^"]*\(".*\)/\1****\2/g; s/\("password": "\)[^"]*\(".*\)/\1****\2/g' ~/.composer/auth.json

      - name: Install Dependencies
        run: |
          composer install --prefer-dist --no-progress -vvv

      - name: Run tests
        run: |
          vendor/bin/phpunit
          vendor/bin/phpcs
          vendor/bin/phpstan analyse
          vendor/bin/psalm
          vendor/bin/phpmd src text cleancode,codesize,controversial,design,naming,unusedcode

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create release archive
        run: |
          zip -r Sterk_GraphQlPerformance.zip app/code/Sterk/GraphQlPerformance

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Sterk_GraphQlPerformance.zip
          asset_name: Sterk_GraphQlPerformance.zip
          asset_content_type: application/zip
